### ISSUE TITLE
What is the diference bewteen instance instance accuracy and class accuracy

### ISSUE THREAD

**Issue by yuchenlichuck** [qq456cvb/Point-Transformers#10]

**Comment by yuchenlichuck** [comment]
For Nico:
**Best Instance Accuracy: 0.588710, Class Accuracy: 0.474499**
For Menghao:
**Best Instance Accuracy: 0.906452, Class Accuracy: 0.872310**
For Hengshuang:
**Best Instance Accuracy: 0.897984, Class Accuracy: 0.851655**

**Comment by qq456cvb** [comment]
Basically, instance accuracy measures the average accuracy across ALL instances, while class accuracy first measures mean accuracy within each class, then average all accuracies from all classes.

**Comment by yuchenlichuck** [comment]
Okay, Thank you so much! Great Job!
