### ISSUE TITLE
Have a problem with "python train_partseg.py"

### ISSUE THREAD

**Issue by ThinhPham24** [qq456cvb/Point-Transformers#14]
I have a problem when I ran "python train_partseg.py". Please give me on how to solve this problem.
![Screenshot from 2021-08-09 02-40-30](https://user-images.githubusercontent.com/58129562/128642340-a402d669-c90b-4622-9951-a528ac06176c.png)

**Comment by qq456cvb** [comment]
Hi, it seems that your hydra version is either too high or too low, please consider installing hydra-core==1.0.1.

**Comment by ThinhPham24** [comment]
HI, Thank you for your replying, I try installing but I still met the same problem.

**Comment by qq456cvb** [comment]
For a simple fix, you can just comment out that line. This line just prints the configuration json and has nothing to do with the real training process.

**Comment by ThinhPham24** [comment]
Thank you, I will try fix this problem.
