### ISSUE TITLE
main() got an unexpected keyword argument 'config_name'

### ISSUE THREAD

**Issue by bucky999** [qq456cvb/Point-Transformers#2]
运行的时候报错了，
main() got an unexpected keyword argument 'config_name'
请问如何读取config.yaml配置文件

**Comment by qq456cvb** [comment]
确认安装的hydra-core版本在1.0.0及以上

**Comment by AI-Hello** [comment]
我这个安装hydra-core1.4版本还是出错是什么原因呢
