### ISSUE TITLE
Why the test accuracy can be higher than train accuracy?

### ISSUE THREAD

**Issue by Gary769581667** [qq456cvb/Point-Transformers#27]
Hello,

When I used ModelNet 40 and other dataset to train Point Transformer(Hengshuang), I found after the 3rd epoch, the test accuracy would be higher than train accuracy.  It makes no sense a model could perform better when processing unseen data, right? Do you also meet this phenomenon?

**Comment by qq456cvb** [comment]
This is possible, given that strong data augmentation is used, e.g., random scale, shift, drop (https://github.com/qq456cvb/Point-Transformers/blob/master/train_cls.py#L109).

**Comment by qq456cvb** [comment]
No recent activities. Closed
