### ISSUE TITLE
Problem about train_partseg

### ISSUE THREAD

**Issue by SkySeWker** [qq456cvb/Point-Transformers#37]
ModuleNotFoundError: No module named 'models.Hengshuang'??

**Comment by qq456cvb** [comment]
I have tested with hydra==1.2.0 with no problems, can you pull the latest code and try again?

**Comment by SkySeWker** [comment]
I wil try that.Thanks for your reply!

**Comment by SkySeWker** [comment]
我尝试过pip install hydra-core --upgrade 也成功了
但是依旧有这样的错误&nbsp; 怎么会 module not found?
&nbsp;
classifier = getattr(importlib.import_module('models.{}.model'.format(args.model.name)), 'PointTransformerSeg')(args).cuda()
&nbsp; &nbsp; #######################
&nbsp; &nbsp; ####error executing job with overridrs:[]
&nbsp; &nbsp; ##### modulenotFoundERROR: no module named&nbsp; &nbsp;'models.Hengshuang '
&nbsp; &nbsp;&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qq456cvb/Point-Transformers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 中午12:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qq456cvb/Point-Transformers] Problem about train_partseg (Issue #37)





 
I have tested with hydra==1.2.0 with no problems, can you pull the latest code and try again?

**Comment by qq456cvb** [comment]
Make sure you have exported current directory to env variable `PYTHONPATH`

**Comment by qq456cvb** [comment]
Hi,

You can currently borrow the code from L133 of train_cls.py to test the results. In order to visualize, you can use visdom with labels set. I will update test files once I have more time.
