### ISSUE TITLE
question about pytorch version

### ISSUE THREAD

**Issue by amiltonwong** [qq456cvb/Point-Transformers#4]
Hi, @qq456cvb,

I got the error `RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:50` . The details is here (https://gist.github.com/amiltonwong/9feaaa7d91721ccf6ad8a0d9b5d27d56)

The version of pytorch in my system is v1.3. Which version should we use?

Thanks!

**Comment by qq456cvb** [comment]
It seems that you didn't install PyTorch with cuda support, or your GPU might be dysfunctional.

**Comment by amiltonwong** [comment]
Thanks for your reply. I refactor the code. And it runs smoothly using the original system setting.

**Comment by Dookas** [comment]
What was the solution to the problem here.  I have run into the same issue
