### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by GCH-upup** [qq456cvb/Point-Transformers#9]
I have installed Torch  and CUDA，and my computer system also has GPU.
![QQ截图20210411145948](https://user-images.githubusercontent.com/79844787/114295333-31dac880-9ad7-11eb-964f-dfbb8e59135e.png)
![QQ截图20210411150139](https://user-images.githubusercontent.com/79844787/114295336-37d0a980-9ad7-11eb-9b0d-339f9f6d0e2b.png)
However, this model still is successfully transformed to CUDA. As this
![QQ截图20210411150658](https://user-images.githubusercontent.com/79844787/114295405-9f86f480-9ad7-11eb-9900-7883ebfc358d.png)
How to solve this problem？

**Comment by qq456cvb** [comment]
The error is indicating that you are using a version of Pytorch without CUDA (1.7.1 + cpu), try installing a GPU version of Pytorch .

**Comment by GCH-upup** [comment]
I have modified my Anaconda envs including Python=3.7, CUDA=10.1 and torch is 1.6.0+cu101. Such as this
![QQ截图20210414131705](https://user-images.githubusercontent.com/79844787/114658591-a8203a80-9d24-11eb-9da2-e105f3a293ed.png)
But this model still can not be processed.
![QQ截图20210414132630](https://user-images.githubusercontent.com/79844787/114658860-1d8c0b00-9d25-11eb-9161-474dc382ee8c.png)
Can you show me your default of Pytorch, CUDA and Python?  Thank you

**Comment by GCH-upup** [comment]
This program has run in Pycharm!  thank for your answer!
